include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-bird
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

LUCI_TITLE:=BIRD2 antifilter web interface
LUCI_DEPENDS:=+bird +luci-base +rpcd-mod-ucode +ucode-mod-fs +ucode-mod-uci
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-2.0-or-later

include $(TOPDIR)/feeds/luci/luci.mk
